import { ITestimonial } from "@/interface/testimonial.interface";

export const testimonials: ITestimonial[] = [
  {
    title: "Dank QuinBook konnten wir weiter wachsen!",
    name: "David Middleton",
    address: "Bewilder Box Brighton (England)",
    image: "/testimonial/david.jpg",
    shortDescription:
      "Der Fokus auf Freizeitanbieter und Escape Room Betreiber, der wirklich persönliche Support, bei dem man sich nicht nur wie eine Kundenummer fühlt und dass man eigentlich alles aus einer Hand bekommt, brachte uns direkt zu QuinBook. Heute blicken wir nicht mehr zurück und können uns gar nicht mehr vorstellen, mit etwas anderem zu arbeiten. Wir sind rundum zufrieden!",
    longDescription: `<h2 style='margin-top:2.0pt;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;font-size:17px;font-family:"Calibri Light",sans-serif;color:#2E74B5;font-weight:normal;'>Ausf&uuml;hrlicher Bericht Bewilder Box:</h2>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Bewilder Box wurde 2016 er&ouml;ffnet, und eine unserer ersten Aufgaben war es, eine Buchungssoftware zu finden. Nach einigen Online-Recherchen entschieden wir uns f&uuml;r ein System, das zu dieser Zeit in der britischen Industrie recht h&auml;ufig verwendet wurde. In unseren Augen sah es gut aus, schien alles zu bieten, was wir brauchten, und kostete nicht viel.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Wir hatten hier und da ein paar Probleme. Es war frustrierend, dass wir unsere E-Mails nicht individuell anpassen konnten, ebenso wie die eher schleppende Reaktion auf viele unserer Unterst&uuml;tzungsbed&uuml;rfnisse, aber wir haben weiter gearbeitet und all die wunderbaren versprochenen Funktionen erwartet, die auf der Roadmap standen.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Mit der Zeit erschienen die neuen Funktionen nicht mehr. Mit dem Wachstum unseres Unternehmens wuchs auch unsere Frustration &uuml;ber die Software, da wir erkannten, dass sie viele der Dinge, die wir zur Unterst&uuml;tzung unserer gr&ouml;&szlig;eren Struktur ben&ouml;tigten, nicht bieten w&uuml;rde. Wir begannen, neue Software zu beschaffen, um die L&uuml;cken zu f&uuml;llen, was wiederum die Kosten erh&ouml;hte, nicht nur f&uuml;r die Software selbst, sondern auch f&uuml;r die Arbeitskr&auml;fte, die f&uuml;r den Datentransfer zwischen den Systemen ben&ouml;tigt wurden. Dadurch erh&ouml;hte sich auch die Wahrscheinlichkeit menschlichen Versagens, und menschliches Versagen kostete uns in der Regel am Ende Geld in erstatteten Spielen.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Ein zuf&auml;lliges Treffen mit dem Quinbook-Team auf der ERIC-Konferenz der britischen Escape Room Industrie im Jahr 2018 machte uns klar, dass es eine weitaus bessere Option gibt. Eine Option, die viele europ&auml;ische Branchenf&uuml;hrer bereits angenommen hatten. Innerhalb von 6 Monaten hatten wir den Wechsel vollzogen, und wir haben nie zur&uuml;ckgeschaut.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Der gr&ouml;&szlig;te Reiz f&uuml;r Bewilder Box war vierfach:</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Escape Room-Fokus</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>W&auml;hrend unser altes Buchungssystem f&uuml;r den Einsatz in verschiedenen Branchen konzipiert war, war Quinbook auf Escape Rooms ausgerichtet. Dies bedeutete, dass jede Funktion und jedes Feature, ob Front- oder Backend, auf unsere spezifischen Anforderungen abgestimmt war. Es bedeutete auch, dass das Team uns verstand, wenn wir mit ihm &uuml;ber unsere Bed&uuml;rfnisse und Schwierigkeiten sprachen!</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Kunden Service</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Unsere Erfahrung im Gespr&auml;ch mit dem Team vor der Migration war fantastisch, und nach Abschluss der Migration waren wir von der Effizienz und Professionalit&auml;t, mit der unsere Anfragen beantwortet wurden, &uuml;berw&auml;ltigt. Dies und die kontinuierliche Einf&uuml;hrung von Aktualisierungen und neuen Funktionen h&auml;tte nicht weiter von dem abweichen k&ouml;nnen, was wir vorher hatten.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Alles aus einer Hand</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Es war von unsch&auml;tzbarem Wert, viele verschiedene Systeme und Prozesse unter ein Dach bringen zu k&ouml;nnen. Pl&ouml;tzlich konnten wir unsere Host Leitf&auml;den, FAQs und Verfahren in dasselbe System bringen, das den Mitarbeitern ihre Schichten zur Verf&uuml;gung stellte, was wiederum direkt mit unseren Buchungen verbunden war. Wir konnten Geld sparen, indem wir unsere Software-Lizenzen konsolidierten, weniger Zeit f&uuml;r die Pflege konsistenter Daten zwischen den Systemen aufwenden und weniger Geld f&uuml;r kostspielige menschliche Fehler, die sich auf die Kundenerfahrung auswirken k&ouml;nnten.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Anpassung</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Quinbook bot uns die M&ouml;glichkeit, seine Funktionen granular anzupassen. Sei es die Verwendung von HTML zur Erstellung unserer eigenen E-Mail-Vorlagen, die Modifizierung des Kunden-Ticket-Shops oder die Konfiguration des &apos;Rules Manager&apos;, um Mitarbeiter zu benachrichtigen, wenn ein bestimmter Platz gebucht wurde - wir haben die Freiheit geliebt, die uns gew&auml;hrt wurde, um unser Gesch&auml;ft so zu f&uuml;hren, wie wir wollen.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Wieder einmal finden wir uns auf Expansionskurs, aber dieses Mal haben wir nicht das Gef&uuml;hl, dass wir zur&uuml;ckgehalten werden, sondern eine Plattform, die alle Aspekte unseres wachsenden Gesch&auml;fts voll unterst&uuml;tzt.</span></p>`,
  },
  {
    title: "Von Freizeit Betreiber FÜR Freizeit Betreiber",
    name: "Julia",
    address: "Elude Escape Rooms, Sidney, Australien",
    image: "/testimonial/julia.jpg",
    shortDescription:
      "Das Quinbook Team hat sowohl Background IN der und Leidenschaft FÜR die Branche. Dadurch weiß es perfekt, welche Funktionen wir als Betreiber benötigen und in welche Richtung Quinbook fortwährend weiterentwickelt werden muss.",
    longDescription: `<h2 style='margin-top:2.0pt;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;font-size:17px;font-family:"Calibri Light",sans-serif;color:#2E74B5;font-weight:normal;'>Ausf&uuml;hrlicher Bericht Elude:</h2>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Die Elude Escape Rooms sind seit 2017 ge&ouml;ffnet, und wir haben ein Buchungssystem verwendet, das urspr&uuml;nglich f&uuml;r Haunted Houses konzipiert war und f&uuml;r die Nutzung von Escape Rooms angepasst wurde.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Darren und ich verbrachten Stunden damit, viele verschiedene Optionen zu recherchieren, um das Beste f&uuml;r uns zu finden. &nbsp;Im Laufe der Zeit stellten wir jedoch fest, dass es nicht immer unseren Bed&uuml;rfnissen entsprach, und wir hatten M&uuml;he, das System f&uuml;r uns effizient zu gestalten.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Es war an der Zeit, den Forschungsprozess wieder aufzunehmen.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>QuinBook habe ich &uuml;ber Google gefunden.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Ich glaube, sie waren &uuml;berrascht, von einem australischen Unternehmen zu h&ouml;ren, da sie in Deutschland ans&auml;ssig sind. &nbsp;Nachdem wir uns das System jedoch angesehen und eine Demonstration von Heiko erhalten hatten, waren wir sehr beeindruckt von dem, was sie zu bieten hatten.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Wir freuen uns, dass wir ihr erster australischer Kunde sind und QuinBook bei der Einrichtung f&uuml;r den australischen Markt unterst&uuml;tzt haben.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Der Implementierungsprozess war ein Kinderspiel, mit au&szlig;ergew&ouml;hnlicher Unterst&uuml;tzung von QuinBook. &nbsp;Wenn etwas nicht funktioniert, wird es umgesetzt, und wenn man eine neue Idee vorschl&auml;gt, wird diese &uuml;bernommen und es wird immer nach M&ouml;glichkeiten gesucht, das System zu verbessern.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Wir sind seit Juni 2019 ein gl&uuml;cklicher Kunde. Quinbook wurde von Escape Room-Besitzern f&uuml;r Escape Room-Besitzer entworfen. Es gab mehrere Dinge, die unser Interesse geweckt hat.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>TicketShop</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Uns gefiel das dynamische Aussehen des Frontends und die benutzerfreundliche Gestaltung. &nbsp;Es erm&ouml;glicht den Kunden, alle R&auml;ume auf einmal zu sehen, was Mehrfachbuchungen so viel einfacher macht. Es hat unserem Unternehmen definitiv geholfen mehr Conversions auf unserer Website zu erzielen.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Leichte Bedienbarkeit</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Was wir absolut lieben ist der einfachen Zugang zum Backend des Systems, der es uns erm&ouml;glicht, &Auml;nderungen im laufenden Betrieb vorzunehmen, Buchungen anzunehmen, Reservierungen anzulegen und Slots zu blockieren.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Das System ist sehr benutzerfreundlich und auch mobil, sowohl im Back- als auch im Frontend. Wir haben immer viel zu tun und zu wissen, dass mir das System nicht nur viel Arbeit abnimmt, sondern ich mich auch darauf verlassen kann, ist so wichtig.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Funktionen, die wir lieben</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Quinbook verf&uuml;gt &uuml;ber einzigartige Benutzerzugriffs-, Berichts- und Kampagnenfunktionen zur Durchf&uuml;hrung von Werbeaktionen.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Es l&auml;sst sich in unseren Google-Kalender integrieren, wir k&ouml;nnen verschiedene ma&szlig;geschneiderte E-Mails und Geschenkgutscheinvorlagen einrichten und fast alles individuell anpassen.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Darren wurde die Arbeit durch die Implementierung mehrerer Ticket-Shops sehr erleichtert. Wir k&ouml;nnen den Kunden auf eine Dankesch&ouml;n-Seite auf unserer eigenen Website schicken, was f&uuml;r Analysen sehr n&uuml;tzlich ist. Einige Systeme erlauben diese Funktion nicht.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Die Erstellung und Replikation von Zeitslots ist leicht anpassbar.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Au&szlig;erdem kommen bald neue Funktionen hinzu, die fantastisch sind und auf die wir kaum warten k&ouml;nnen.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Die beste Funktion, die sehr bald kommt, ist, dass man dem System Ressourcen mitteilen kann. Wenn man nur 2 Mitarbeiter hat, werden nach zwei Buchungen die weiteren Zeitslots automatisch blockiert, so dass man nie mit Buchungen ohne Personal erwischt wird.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Digitale Verzichtserkl&auml;rungen und vieles mehr.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Wenn du sehen m&ouml;chtest, wie es aussieht, besuche unsere Website unter&nbsp;</span><a href="http://www.eludegames.com.au/book-now"><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>www.eludegames.com.au/book-now</span></a><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>.</span></p>`,
  },
  {
    title: "Die All-In-One-Lösung",
    name: "Sylvia Coman",
    address: "Mysteria Escape Bückenburg, Deutschland",
    image: "/testimonial/sylvia.jpg",
    shortDescription:
      "Uns hat das Gesamtpaket überzeugt. Die pure Bandbreite an Features macht viele andere Softwarelösungen einfach überflüssig. Das spart Geld und erlaubt es uns, auf unser Kerngeschäft zu fokussieren.",
    longDescription: `<p>Ausf&uuml;hrlicher Bericht Mysteria Escape</p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Wie alles anfing</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Mysteria Escape ist seit August 2018 am Markt. Vor der Er&ouml;ffnung hatte ich mir in Wordpress durch Plug-Ins selber einen Ticketshop mit Online-Zahlung gebaut. Diese L&ouml;sung hat einmalig 50 Euro gekostet und war grunds&auml;tzlich erst mal nicht schlecht, aber wir mussten sehr viel anpassen, damit es so ist, wie wir es brauchten. Einige Monate vor der Er&ouml;ffnung wurden wir dann auf QuinBook aufmerksam und haben uns in einer Websession die Software vorf&uuml;hren lassen. Wir waren ja Neulinge und konnten selber ja noch gar nicht definieren, welche Features eine Buchungs- und Management Software haben sollte. Umso mehr waren wir geflasht und uns wurde nach der Websession erst richtig bewusst, wie viel administrativen Aufwand wir uns ersparen k&ouml;nnen, wenn wir gleich eine vern&uuml;nftige L&ouml;sung lizensieren. Wir h&ouml;rten auf unser Bauchgef&uuml;hl und wurden Teil der QB-Familie. Diese Entscheidung haben wir NIE bereut.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Features, die wir lieben</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Zeiterfassung</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Wir haben mittlerweile 7 Mitarbeiter (6 Gamemaster und eine Reinigungskraft). Jeder Mitarbeiter hat ein QB-Konto. Nach dem Einloggen k&ouml;nnen sie die Stempeluhr aktivieren und somit ihre Arbeitszeit festhalten. Auch Pausen k&ouml;nnen gestempelt werden. Urlaub tragen wir auch in QB ein.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Am Ende des Monats brauche ich nur in die Mitarbeiterverwaltung gehen und kann mir dort in wenigen Schritten die Stundenzettel exportieren. Die gebe ich dann sowohl meinen Mitarbeitern als auch meiner Steuerberaterin und mehr muss ich f&uuml;r die Lohnabrechnung nicht machen. &nbsp;Super einfach!</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Berechtigungen</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&Uuml;ber die Benutzerrechte kann ich sehr genau einstellen was jeder Mitarbeiter in QB sehen kann. Diese Funktion macht es m&ouml;glich, dass z.B. auch meine Reinigungskraft ein QB-Konto hat, damit sie ihre Zeit stempeln kann.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Meine Mitarbeiter k&ouml;nnen die Einstellungen inkl. Erlebnisse und Artikel nicht ver&auml;ndern. Auch Einblicke in Statistiken oder Buchhaltung haben nur mein Partner und ich.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Jeder Mitarbeiter kann aber problemlos Termine umbuchen, Gutscheine vor Ort verkaufen &nbsp;und Zahlungen entgegennehmen.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Schichtplanung</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>In den Anf&auml;ngen gab es bei QB nur eine einfache Schichtplanung. Die war auch gut - aber Ende 2019 wurde die neue Schichtplanung eingef&uuml;hrt. Vorher konnte ich immer nur eine Woche im Voraus planen, weil die Mitarbeiter sich einfach immer nur f&uuml;r die n&auml;chste Woche beworben haben. Mit der neuen Schichtplanung gibt jeder seine Verf&uuml;gbarkeit(en) an und das ist viel simpler. Meine Mitarbeiter tragen ihre Verf&uuml;gbarkeit teilweise 6-8 Wochen im Voraus ein. Dadurch kann ich jetzt immer schon 2 oder 3 Wochen im Voraus planen.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Wir kommunizieren nicht auf anderen Kan&auml;len wie Google Calendar oder in irgendwelchen Excel-Dateien. Alles ist in QB zu finden. F&uuml;r uns ist die Schichtplanung eine riesen Erleichterung.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Einfache Erstellung einer Buchung auch vom Handy</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Sehr oft bekommen wir Anrufe von Kunden, die kurzfristig buchen m&ouml;chten. Wir haben unseren Ticket Shop so eingestellt, dass man bis zu 12 Stunden vor dem Termin online buchen kann. Versucht man innerhalb der 12 Stunden zu buchen, kann man zwar noch sehen welche Termine frei sind, aber es erscheint ein Popup mit der Aufforderung uns anzurufen.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;Auf diese Weise haben wir schon viele Buchungen erhalten und viele Kunden sagen auch: &bdquo;Naja, bei XXX kann man ja nur 2 Tage im Voraus buchen. Da habe ich nicht angerufen, denn ich sehe ja nicht ob &uuml;berhaupt noch was frei ist.&ldquo;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Selbst wenn wir nicht gerade vor einem PC sitzen, ist das Anlegen einer Buchung ganze einfach vom Handy aus m&ouml;glich. Ich stelle den Kunden auf Lautsprecher, &ouml;ffne QB, gehe in den Kalender und &ouml;ffne den gew&uuml;nschten Termin f&uuml;r den gew&auml;hlten Raum. Es &ouml;ffnet sich dann automatisch eine neue Buchung. Ich gebe Anzahl der Spieler, Name und E-Mailadresse des Kunden ein (Telefonnummer kopiere ich sp&auml;ter aus meinem Handy) und fertig ist die Buchung.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Blockierung von Terminen</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Wenn es mal schneller gehen soll und es nicht relevant ist, dass der Kunde eine Best&auml;tigung per E-Mail bekommt, dann blockieren wir oft auch erst den Termin und schreiben nur den Namen und die Telefonnummer dazu. Wenn der Kunde dann zum Termin vor Ort ist, verwandeln wir die Blockierung in eine Buchung am PC. F&uuml;r solche F&auml;lle haben wir einen &bdquo;Dummy-Kunden&ldquo;, denn sonst m&uuml;sste ich auch die E-Mail Adresse des Kunden erst wieder erfragen und bei kurzfristigen Buchung oder auch Gutscheinverk&auml;ufen vor Ort ist ein Platzhalterkunde ideal und die Buchhaltung auch sauber. &nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Werbeaktionen</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Durch das Anlegen von Kampagnen habe ich schon einige Werbeaktionen durchgef&uuml;hrt. Z.B . zur Einf&uuml;hrung unserer Kinder iPad-Tour habe ich 10% Rabatt auf Buchungen f&uuml;r einen gewissen Zeitraum gew&auml;hrt. Der Rabatt war dann auch nur auf die Tour anwendbar und nicht auf unseren Escape Room.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Man kann jedem Rabatt einen Alias-Namen geben. In dem Fall nannten wir es SUMMER2019. Im Ticket Shop kann der Kunde dann diesen Coupon Code eingeben und erh&auml;lt automatisch den Rabatt.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Mehrere Ticketshops</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Nicht alles in einem Ticket Shop anzeigen zu m&uuml;ssen finden wir besonders klasse. Wir haben insgesamt drei Tickt Shops auf unserer Seite. Einen f&uuml;r Escape Rooms, einen f&uuml;r die Outdoor Touren und einen f&uuml;r die Gutscheine. So wird der Kunde nicht mit einer Riesenauswahl &uuml;berfordert und findet sofort wonach er sucht.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Regelmanager</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Dieses Feature, das in 2019 eingef&uuml;hrt wurde, nutzen wir sehr intensiv. Nat&uuml;rlich bekommt jeder Kunde eine Best&auml;tigungsemail nachdem er gebucht hat. ABER: zus&auml;tzlich schicken wir noch eine zweite E-Mail, die wir komplett selber definiert haben. Denn die Information, die ich meinen Kunden schicken m&ouml;chte, ist sehr unterschiedlich, je nachdem was sie gebucht haben. Die E-Mail f&uuml;r den Escape Room enth&auml;lt z.B. folgendes: seid p&uuml;nktlich, nicht betrunken, etc. Die E-Mail f&uuml;r die iPad-Tour hat ganz andere Informationen: denkt an wetterfeste Kleidung, bringt Getr&auml;nke mit, hier ist die Einladungskarte zum Downloaden, etc.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Aber am besten kommt die E-Mail zu unserem neuen Raum &bdquo;Das Geheimnis des Bermuda Dreiecks&ldquo; an. Diese E-Mail geht 24 Stunden vor dem gebuchten Termin an den Kunden und ist im Grunde der Auftakt zum Abenteuer. Der Kunde wird aufgefordert den CHECK-IN f&uuml;r ihren Flug online durchzuf&uuml;hren, denn das Abenteuer beginnt mit einem Flug nach Miami und dazu braucht man nat&uuml;rlich Boarding-Tickets. Wir sammeln &uuml;ber ein Formular auf unserer Webseite die Namen der Spieler und k&ouml;nnen dann personalisierte Tickets ausstellen. Die E-Mail wird von QB automatisch generiert und verschickt. Man hat in QB auch den absoluten &Uuml;berblick welche E-Mails der Kunde erhalten hat, ob sie angekommen sind und ob die E-Mails gelesen wurden.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Fazit</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>QB ist sicher nicht die billigste L&ouml;sung auf dem Markt, aber sie wurde f&uuml;r den Betrieb von Escape Rooms entwickelt. F&uuml;r uns ist es jeden Pfennig wert. Au&szlig;erdem gibt es bei QB keinen Stillstand. Die Software wird stetig weiterentwickelt und wir freuen uns jetzt schon auf die Features, die in 2020 hinzukommen werden.&nbsp;</span></p>
<p><span style='font-size:16px;font-family:"Arial",sans-serif;'>Last but not least&hellip;. der Support bei QB kann sich wirklich sehen lassen. Wenn es mal Probleme gab oder wir nicht genau wussten wie man etwas anlegt oder ausf&uuml;hrt, dann hat der Support immer schnell geholfen.</span></p>`,
  },
  {
    title: "Gekommen, um zu bleiben!",
    name: "Lukas Rauscher",
    address: "Crime Runners, Wien, Österreich",
    image: "/testimonial/lukas.jpg",
    shortDescription:
      "Es gibt am Markt nichts Vergleichbares mit dieser Fülle an Features mit einem dermaßen fairen Preismodell. Als einer der ersten internationalen Kunden sind wir über die Jahre regelrechte Quinbook-Fans geworden.",
    longDescription: `<h3 style='margin-top:2.0pt;margin-right:0in;margin-bottom:.0001pt;margin-left:0in;font-size:16px;font-family:"Calibri Light",sans-serif;color:#1F4D78;font-weight:normal;'>Ausf&uuml;hrlicher Bericht Crime Runners</h3>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Wir haben Crime Runners 2015 gegr&uuml;ndet und haben quasi alle Buchungsl&ouml;sungen durch. Eine eigens entwickelte L&ouml;sung und dann andere bekannte Buchungssysteme. Die eigene L&ouml;sung machte viel zu viele Probleme und bremste unser Wachstum. Der Aufwand wurde enorm. Als wir dann zu einer anderen L&ouml;sung, die auf den ersten Blick OK war, umstiegen, wurde schnell klar, dass es mehr &bdquo;Schein als Sein&ldquo; war. Das Design war sch&ouml;n, aber es gab nur rudiment&auml;re Funktionen und es wurde wohl mehr Geld in Vertrieb gesteckt, als in Weiterentwicklung. Und dann das Pricing: Umsatzbeteiligungen sind in unseren Augen einfach nicht OK f&uuml;r ein Drittanbietersystem. Schnell konnte ich mir ausrechnen, dass wenn wir in dem Tempo weiterwachsen wir bald vierstellige Betr&auml;ge pro Monat zahlen w&uuml;rden. Als wir das Gespr&auml;ch mit dem damaligen Anbieter &nbsp;suchten, wurden wir nur abgehandelt. Ich recherchierte damals sehr lange und arbeitete mich in gef&uuml;hlt jedes Buchungssystem am Markt ein. Kaum eine L&ouml;sung konnte mich &uuml;berzeugen. Und dann stie&szlig; ich auf Heiko von QuinBook. Damals war das noch nicht Live, aber sie bereiteten den Launch und die Internationalisierung vor. Ich merkte schnell, dass da etwas Gro&szlig;es am Entstehen war und so trafen wir uns mit Albert und Heiko und sie zeigten uns alles. Ich war baff: QuinBook war alles was ich gesucht hatte und sogar um einiges mehr. Das Sch&ouml;nste: Wir verwenden gar nicht alle Funktionen, sondern suchen uns aus, was f&uuml;r unser Business passt und f&uuml;r was wir unsere eigenen etablierten Prozesse nutzen. Aber dass es diese F&uuml;lle an Funktionen gibt, haut mich einfach um. Das wurde eindeutig von Unternehmern entwickelt, die das f&uuml;r ihr eigenes Freizeitbusiness nutzen wollten und damit auch die Branche besser verstehen.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Individualisierung</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Allein die zahlreichen Individualisierungs-M&ouml;glichkeiten, wie etwa der E-Mail Regelmanager und der automatische Versand mit individuell w&auml;hlbaren Triggern, gibt einem in den Bereichen CRM und Marketing zahlreiche M&ouml;glichkeiten. Samt Kundendatenbank ist das einfach ein rundum Paket.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Einfache Bedienung, komplexe Funktionen</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>So einfach es war, QuinBook auf unser System aufzusetzen, so erstaunt bin ich, wie viele Funktionen es gibt. Oft w&uuml;nsche ich mir ein neues Feature, um dann zu merken, dass man das bereits mit QuinBook umsetzen kann. Nichts, aber wirklich nichts Vergleichbares, fandich in meiner Buchungssystem-Marathon-Recherche zuvor.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Handschlagqualit&auml;t und nachhaltige Weiterentwicklung</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Man merkt, dass es einen st&auml;ndigen Austausch seitens QuinBook mit den Kunden gibt. Ich erfahre das st&auml;ndig, wenn ich mit neuen Vorschl&auml;gen antanze und ich sehe es auch an den internen Foren, bei dem andere Betreiber W&uuml;nsche und Anregungen &auml;u&szlig;ern. Da sitzen Menschen und keine Investoren, die rein nach Zahlen gehen. Genau diese Einbindung der Kunden ist der Schl&uuml;ssel zu st&auml;ndigem Wachstum, von dem eigentlich zahlengetriebene Menschen nur tr&auml;umen w&uuml;rden. Top-Support mit allen menschlichen Ecken und Kanten, die ich sehr sch&auml;tze.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>St&auml;ndig neue Features</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Dank der Art und Weise, wie das QuinBook Team die Kommunikation angeht und auf Kundenw&uuml;nsche eingeht, kommen st&auml;ndig neue Features hinzu. Sind die Vorschl&auml;ge gut, werden sie auch wirklich umgesetzt. Selbst gro&szlig;e Featurew&uuml;nsche, die lange in der Entwicklung ben&ouml;tigen. Voraussetzung ist nat&uuml;rlich, dass ein Feature Sinn macht. Eine kleine Auswahl der letzten Jahre:</span></p>
<ul style="list-style-type: disc;">
    <li><span style='line-height:107%;font-family:"Arial",sans-serif;font-size:16px;'>Einfacher Rabatt direkt auf einen individuellen Slot</span></li>
    <li><span style='line-height:107%;font-family:"Arial",sans-serif;font-size:16px;'>Rabattierte Gutscheine</span></li>
    <li><span style='line-height:107%;font-family:"Arial",sans-serif;font-size:16px;'>QuinGames</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>W&auml;hrend der Coronakrise k&auml;mpften besonders Freizeitunternehmen darum, irgendwie in den Lockdowns arbeiten zu k&ouml;nnen und unternehmerische Kontrolle zur&uuml;ckzuerlangen. QuinBook stampfte einen voll funktionalen Editor aus dem Boden, um individuelle Point &amp; Click Adventures zu erstellen und gab Betreibern damit die M&ouml;glichkeit, abseits des Lockdowns, digitale Erlebnisse zu kreieren. Und f&uuml;r QuinBook Kunden war das kostenlos. Eine Entscheidung vor der ich heute noch den allergr&ouml;&szlig;ten Respekt habe.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Faire Preise</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Das Gesamtpaket &uuml;berzeugt auch, wenn es um das Preismodell geht. Ich bin ein gro&szlig;er Fan von kundenfreundlichen Flatrates, weil es einem die Kostenplanung sehr viel einfacher macht und man nicht das Gef&uuml;hl hat, dass st&auml;ndig das Taxameter rennt. Ich kenne keine digitale L&ouml;sung, die auch nur ann&auml;hernd den Funktionsumfang von QuinBook hat. Und mit einer Flatrate anstelle einer Umsatzbeteiligung schon gar nicht.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><strong><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Fazit:</span></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>Wir waren der erste internationale QuinBook Kunde und sind gekommen, um zu bleiben. Mittlerweile sind es sieben Jahre Zusammenarbeit, auf die wir zur&uuml;ckblicken k&ouml;nnen und wir haben alle Holprigkeiten und Widrigkeiten in der Branche bereits gemeinsam erlebt. Was soll ich sagen: Wir sind QuinBook Fans.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri",sans-serif;'><a href="http://www.crimerunners.at"><span style='font-family:"Arial",sans-serif;'>www.crimerunners.at</span></a><span style='font-size:16px;line-height:107%;font-family:"Arial",sans-serif;'>&nbsp;</span></p>`,
  },
];
